In [1]:
import pandas as pd
import numpy as np

## Importing data from Austin Animal Center

In [6]:
intakes = pd.read_csv(r'/Users/philliprichardson/Metis/Module 4/Austin_Animal_Center_Intakes.csv')
outcomes = pd.read_csv(r'/Users/philliprichardson/Metis/Module 4/Austin_Animal_Center_Outcomes.csv')

In [14]:
outcomes.head(20)

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A794011,Chunk,05/08/2019 06:20:00 PM,05/08/2019 06:20:00 PM,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
1,A776359,Gizmo,07/18/2018 04:02:00 PM,07/18/2018 04:02:00 PM,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
2,A821648,NaN,08/16/2020 11:38:00 AM,08/16/2020 11:38:00 AM,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
3,A720371,Moose,02/13/2016 05:59:00 PM,02/13/2016 05:59:00 PM,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff
4,A674754,NaN,03/18/2014 11:47:00 AM,03/18/2014 11:47:00 AM,03/12/2014,Transfer,Partner,Cat,Intact Male,6 days,Domestic Shorthair Mix,Orange Tabby
5,A659412,Princess,10/05/2020 02:37:00 PM,10/05/2020 02:37:00 PM,03/24/2013,Adoption,NaN,Dog,Spayed Female,7 years,Chihuahua Shorthair Mix,Brown
6,A814515,Quentin,05/06/2020 07:59:00 AM,05/06/2020 07:59:00 AM,03/01/2018,Adoption,Foster,Dog,Neutered Male,2 years,American Foxhound/Labrador Retriever,White/Brown
7,A689724,*Donatello,10/18/2014 06:52:00 PM,10/18/2014 06:52:00 PM,08/01/2014,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black
8,A680969,*Zeus,08/05/2014 04:59:00 PM,08/05/2014 04:59:00 PM,06/03/2014,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,White/Orange Tabby
9,A684617,NaN,07/27/2014 09:00:00 AM,07/27/2014 09:00:00 AM,07/26/2012,Transfer,SCRP,Cat,Intact Female,2 years,Domestic Shorthair Mix,Black
10,A742354,Artemis,01/22/2017 11:56:00 AM,01/22/2017 11:56:00 AM,01/20/2010,Return to Owner,NaN,Cat,Neutered Male,7 years,Domestic Shorthair Mix,Blue/White
11,A681036,NaN,06/11/2014 05:11:00 PM,06/11/2014 05:11:00 PM,06/09/2014,Transfer,Partner,Cat,Intact Male,2 days,Domestic Shorthair Mix,Brown Tabby
12,A803149,*Birch,08/31/2019 04:26:00 PM,08/31/2019 04:26:00 PM,08/08/2019,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair,Brown Tabby
13,A698049,Luigi,03/16/2015 02:50:00 PM,03/16/2015 02:50:00 PM,06/05/2014,Transfer,Partner,Cat,Spayed Female,9 months,Domestic Medium Hair Mix,Black/White
14,A773792,NaN,06/05/2018 03:30:00 PM,06/05/2018 03:30:00 PM,05/05/2018,Euthanasia,Suffering,Cat,Intact Male,4 weeks,Domestic Shorthair Mix,Orange Tabby
15,A725795,NaN,05/03/2016 12:39:00 PM,05/03/2016 12:39:00 PM,04/15/2016,Euthanasia,Underage,Other,Unknown,2 weeks,Opossum,Gray
16,A730621,*Liza,09/10/2016 06:59:00 PM,09/10/2016 06:59:00 PM,05/18/2016,Adoption,NaN,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Calico
17,A765349,Einstein,06/08/2018 01:04:00 PM,06/08/2018 01:04:00 PM,01/18/2009,Adoption,Foster,Dog,Neutered Male,9 years,Chihuahua Shorthair Mix,Tricolor
18,A760697,Star,10/26/2017 03:22:00 PM,10/26/2017 03:22:00 PM,10/23/2007,Transfer,Partner,Dog,Intact Male,10 years,Yorkshire Terrier Mix,Brown/Black
19,A767231,Millie,02/25/2018 05:19:00 PM,02/25/2018 05:19:00 PM,02/25/2017,Return to Owner,NaN,Dog,Spayed Female,1 year,Jack Russell Terrier/Chihuahua Shorthair,White/Tan

In [18]:
df = intakes.merge(outcomes, left_on = ['Animal ID','Animal Type'], right_on = ['Animal ID','Animal Type'])

In [19]:
df.columns

Index(['Animal ID', 'Name_x', 'DateTime_x', 'MonthYear_x', 'Found Location',
       'Intake Type', 'Intake Condition', 'Animal Type', 'Sex upon Intake',
       'Age upon Intake', 'Breed_x', 'Color_x', 'Name_y', 'DateTime_y',
       'MonthYear_y', 'Date of Birth', 'Outcome Type', 'Outcome Subtype',
       'Sex upon Outcome', 'Age upon Outcome', 'Breed_y', 'Color_y'],
      dtype='object')

In [33]:
test = (df.groupby(['Animal ID']).DateTime_x.count() > 1).reset_index()

In [41]:
mask = (test['DateTime_x'] == True)

In [43]:
animal_dupes = test[mask]['Animal ID']

In [45]:
df.merge(animal_dupes, left_on = 'Animal ID', right_on = 'Animal ID')

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,...,Name_y,DateTime_y,MonthYear_y,Date of Birth,Outcome Type,Outcome Subtype,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
0,A731435,*Casey,08/08/2016 05:52:00 PM,08/08/2016 05:52:00 PM,Austin (TX),Owner Surrender,Normal,Cat,Neutered Male,5 months,...,*Casey,08/13/2016 12:27:00 PM,08/13/2016 12:27:00 PM,02/22/2016,Transfer,Partner,Neutered Male,5 months,Domestic Shorthair Mix,Cream Tabby
1,A731435,*Casey,08/08/2016 05:52:00 PM,08/08/2016 05:52:00 PM,Austin (TX),Owner Surrender,Normal,Cat,Neutered Male,5 months,...,*Casey,07/29/2016 07:00:00 PM,07/29/2016 07:00:00 PM,02/22/2016,Adoption,NaN,Neutered Male,5 months,Domestic Shorthair Mix,Cream Tabby
2,A731435,*Casey,07/22/2016 10:44:00 AM,07/22/2016 10:44:00 AM,Blue Goose Rd And Giles Lna in Austin (TX),Stray,Normal,Cat,Intact Male,4 months,...,*Casey,08/13/2016 12:27:00 PM,08/13/2016 12:27:00 PM,02/22/2016,Transfer,Partner,Neutered Male,5 months,Domestic Shorthair Mix,Cream Tabby
3,A731435,*Casey,07/22/2016 10:44:00 AM,07/22/2016 10:44:00 AM,Blue Goose Rd And Giles Lna in Austin (TX),Stray,Normal,Cat,Intact Male,4 months,...,*Casey,07/29/2016 07:00:00 PM,07/29/2016 07:00:00 PM,02/22/2016,Adoption,NaN,Neutered Male,5 months,Domestic Shorthair Mix,Cream Tabby
4,A657188,Tommy,11/10/2013 05:19:00 PM,11/10/2013 05:19:00 PM,Austin (TX),Owner Surrender,Normal,Cat,Neutered Male,14 years,...,Tommy,01/26/2014 04:24:00 PM,01/26/2014 04:24:00 PM,06/24/1999,Adoption,Foster,Neutered Male,14 years,Domestic Shorthair Mix,Brown Tabby/White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61336,A786379,Bear,02/08/2019 09:45:00 AM,02/08/2019 09:45:00 AM,1009 Edgecliff Terrace in Austin (TX),Stray,Normal,Dog,Neutered Male,6 years,...,Bear,12/29/2018 07:37:00 PM,12/29/2018 07:37:00 PM,02/22/2012,Rto-Adopt,NaN,Neutered Male,6 years,Akita Mix,Tan/Black
61337,A800028,Eddy,08/25/2019 01:07:00 PM,08/25/2019 01:07:00 PM,Travis (TX),Owner Surrender,Normal,Dog,Neutered Male,1 year,...,Eddy,08/11/2019 03:12:00 PM,08/11/2019 03:12:00 PM,08/15/2018,Adoption,NaN,Neutered Male,11 months,Boxer Mix,Brown Brindle
61338,A800028,Eddy,08/25/2019 01:07:00 PM,08/25/2019 01:07:00 PM,Travis (TX),Owner Surrender,Normal,Dog,Neutered Male,1 year,...,Eddy,08/25/2019 04:24:00 PM,08/25/2019 04:24:00 PM,08/15/2018,Adoption,NaN,Neutered Male,1 year,Boxer Mix,Brown Brindle
61339,A800028,Eddy,07/15/2019 02:45:00 PM,07/15/2019 02:45:00 PM,17310 Lessmann Lane in Travis (TX),Owner Surrender,Normal,Dog,Intact Male,10 months,...,Eddy,08/11/2019 03:12:00 PM,08/11/2019 03:12:00 PM,08/15/2018,Adoption,NaN,Neutered Male,11 months,Boxer Mix,Brown Brindle
61340,A800028,Eddy,07/15/2019 02:45:00 PM,07/15/2019 02:45:00 PM,17310 Lessmann Lane in Travis (TX),Owner Surrender,Normal,Dog,Intact Male,10 months,...,Eddy,08/25/2019 04:24:00 PM,08/25/2019 04:24:00 PM,08/15/2018,Adoption,NaN,Neutered Male,1 year,Boxer Mix,Brown Brindle